application: YOUR-APPLICATION-ID
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /templates
  static_dir: templates

- url: /
  script: server.main.application
  secure: always

- url: /service.*
  script: server.main.application

libraries:
- name: jinja2
  version: latest
- name: django
  version: latest
